//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectricalShop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductItem
    {
        public int CategoryId { get; set; }
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> ItemPrice { get; set; }
        public byte[] ItemImage { get; set; }
        public string ItemCharacteristics { get; set; }
        public string ItemDescription { get; set; }
        public string ItemColor { get; set; }
        public Nullable<int> ItemAmount { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
